[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_core = { path = "../engine_core" }
physics = { path = "../physics" }
world_gen = { path = "../world_gen" }
net = { path = "../net" }
mod_api = { path = "../mod_api" }
render_pipeline = { path = "../render_pipeline" }

rkyv = { version = "0.7", features = ["validation"] }

bevy = "0.13"
